# Generated by Django 5.2.11 on 2026-05-09 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mypoke',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mypoke',
            name='current_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Fire'), (2, 'Water'), (3, 'Grass'), (4, 'Electric'), (5, 'Psychic'), (6, 'Rock'), (7, 'Ghost')], default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(help_text='Base HP for this species'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(help_text='Base level of species (used as reference)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Fire'), (2, 'Water'), (3, 'Grass'), (4, 'Electric'), (5, 'Psychic'), (6, 'Rock'), (7, 'Ghost')], default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(help_text='Base speed for this species'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='xp',
            field=models.IntegerField(default=0, help_text='Base XP (reference only)'),
        ),
        migrations.CreateModel(
            name='BattleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_hp', models.IntegerField()),
                ('opponent_hp', models.IntegerField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('challenger_won', 'Challenger Won'), ('opponent_won', 'Opponent Won')], default='ongoing', max_length=20)),
                ('battle_log_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenger_poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_challenger', to='pokemon.mypoke')),
                ('opponent_poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to='pokemon.mypoke')),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_required', models.IntegerField()),
                ('from_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_into', to='pokemon.pokemon')),
                ('to_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolved_from', to='pokemon.pokemon')),
            ],
            options={
                'unique_together': {('from_pokemon', 'to_pokemon')},
            },
        ),
    ]
