# Generated by Django 5.2.11 on 2026-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_mypoke_current_level_mypoke_current_xp_player_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_starter',
            field=models.BooleanField(default=False, help_text='Appears in starter selection'),
        ),
    ]
