# Generated by Django 6.0.6 on 2026-06-30 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0018_alter_chatroom_members_alter_videocall_date_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocall',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 30, 13, 38, 17, 272918)),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 30, 13, 38, 17, 272896)),
        ),
    ]
