# Generated by Django 5.1.7 on 2025-06-24 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_header', models.CharField(max_length=20)),
                ('post_text', models.CharField(max_length=250)),
                ('post_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
