# Generated by Django 5.1.7 on 2025-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_header',
            field=models.CharField(max_length=30),
        ),
    ]
