# Generated by Django 5.1.7 on 2025-07-20 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(auto_now_add=True, default=datetime.time(14, 18, 51, 617224)),
            preserve_default=False,
        ),
    ]
