# Generated by Django 5.0.6 on 2024-06-17 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('isverified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_details',
            fields=[
                ('vehicle_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_company', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPS_Toll_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(choices=[('', 'From'), ('Mathura', 'Mathura'), ('Aligarh', 'Aligarh'), ('Palwal', 'Palwal'), ('Hathras', 'Hathras')], max_length=100)),
                ('ending_point', models.CharField(choices=[('', 'To'), ('Mathura', 'Mathura'), ('Aligarh', 'Aligarh'), ('Palwal', 'Palwal'), ('Hathras', 'Hathras')], max_length=100)),
                ('uuid_field', models.CharField(max_length=10, null=True)),
                ('vehicle_type', models.CharField(max_length=100, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('charge_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination_reached_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='GPS_Toll_app.vehicle_details')),
            ],
        ),
    ]
