# Generated by Django 5.0.5 on 2024-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_alter_items_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
