# Generated by Django 3.1.6 on 2021-02-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcounter', '0002_mail_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='board',
        ),
    ]
