# Generated by Django 3.2.4 on 2025-02-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_theme_setting_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
