# Generated by Django 4.2.5 on 2023-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_remove_post_image_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_images/<django.db.models.fields.related.ForeignKey>/post_image_<built-in function id>/'),
        ),
    ]
