# Generated by Django 4.2.5 on 2023-10-01 13:16

from django.db import migrations, models
import social_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=social_app.models.get_post_image_filepath),
        ),
    ]
