# Generated by Django 5.1.6 on 2025-03-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_hoteluser_is_verified_hotelvendor_is_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hoteluser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hotelvendor",
            options={},
        ),
        migrations.AddField(
            model_name="hotelvendor",
            name="business_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="hoteluser",
            table="hotel_user",
        ),
        migrations.AlterModelTable(
            name="hotelvendor",
            table="hotel_vendor",
        ),
    ]
