# Generated by Django 5.1.6 on 2025-03-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_hoteluser_options_alter_hotelvendor_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hoteluser",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="hotelvendor",
            name="otp",
        ),
    ]
