# Generated by Django 5.1.6 on 2025-03-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_hoteluser_otp_remove_hotelvendor_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_start_date", models.DateTimeField()),
                ("booking_end_date", models.DateTimeField()),
                ("booking_price", models.FloatField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booked_hotel_name",
                        to="accounts.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booked_user_name",
                        to="accounts.hoteluser",
                    ),
                ),
            ],
        ),
    ]
