# Generated by Django 5.0.6 on 2024-06-24 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0002_alter_profile_bio_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
