# Generated by Django 5.0.6 on 2024-06-24 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('f27f17d6-a42f-4663-b7f7-acb4ec054f8f'), primary_key=True, serialize=False),
        ),
    ]
