# Generated by Django 5.0.6 on 2024-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0006_alter_post_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('post_id', models.UUIDField()),
            ],
        ),
    ]
