# Generated by Django 5.0.6 on 2024-06-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0010_profile_followers_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User',
        ),
    ]
