# Generated by Django 5.0.6 on 2024-06-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0012_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User',
        ),
        migrations.AddField(
            model_name='post',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profile_page.profile'),
            preserve_default=False,
        ),
    ]
