# Generated by Django 5.0.6 on 2024-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_page', '0013_remove_post_user_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
