# Generated by Django 5.1.1 on 2024-10-09 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_remote",
        ),
        migrations.AddField(
            model_name="event",
            name="pub_date",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
